# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4Gesfq8OI3JAydQ8sS9fr2wjgaNbyyd
"""

!pip install streamlit
!pip install sqlalchemy
import sqlite3
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path
from sqlalchemy import create_engine

st.set_page_config(
    page_title="Dashboard Redes Sociais Brasil",
    page_icon="📱",
    layout="wide"
)

sns.set_theme(style="whitegrid")

BASE_DIR = Path.cwd() # Corrected: Use Path.cwd() instead of Path(__file__).parent
CAMINHO_DADOS = BASE_DIR / "simulacao_redes_sociais_brasil.csv"
CAMINHO_BANCO = BASE_DIR / "database" / "redes_sociais.sqlite"


@st.cache_data
def carregar_dados():
    df = pd.read_csv(CAMINHO_DADOS)

    df["data"] = pd.to_datetime(df["data"])

    df["ano"] = df["data"].dt.year
    df["mes"] = df["data"].dt.month
    df["ano_mes"] = df["data"].dt.to_period("M").astype(str)

    df["interacoes"] = (
        df["curtidas"]
        + df["comentarios"]
        + df["compartilhamentos"]
    )

    return df


def criar_banco(df):
    CAMINHO_BANCO.parent.mkdir(exist_ok=True)

    engine = create_engine(
        f"sqlite:///{CAMINHO_BANCO}"
    )

    df.to_sql(
        "redes_sociais",
        engine,
        if_exists="replace",
        index=False
    )

    return engine


df = carregar_dados()
engine = criar_banco(df)

st.title("📱 Dashboard de Redes Sociais no Brasil")

st.write("""
Análise de desempenho das redes sociais considerando
alcance, visualizações, engajamento e tipos de conteúdo.
""")

#-------sidebar--------------

st.sidebar.header("Filtros")

plataformas = sorted(df["plataforma"].unique())
conteudos = sorted(df["tipo_conteudo"].unique())

plataforma_sel = st.sidebar.multiselect(
    "Plataforma",
    plataformas,
    default=plataformas
)

conteudo_sel = st.sidebar.multiselect(
    "Tipo de Conteúdo",
    conteudos,
    default=conteudos
)

anos = sorted(df["ano"].unique())

ano_sel = st.sidebar.multiselect(
    "Ano",
    anos,
    default=anos
)

df_filtrado = df[
    (df["plataforma"].isin(plataforma_sel))
    & (df["tipo_conteudo"].isin(conteudo_sel))
    & (df["ano"].isin(ano_sel))
]
#------kpi---------
st.subheader("KPIs")

col1, col2, col3, col4 = st.columns(4)

col1.metric(
    "Visualizações",
    f"{df_filtrado['visualizacoes'].sum():,.0f}"
)

col2.metric(
    "Alcance",
    f"{df_filtrado['alcance'].sum():,.0f}"
)

col3.metric(
    "Interações",
    f"{df_filtrado['interacoes'].sum():,.0f}"
)

col4.metric(
    "Engajamento Médio",
    f"{df_filtrado['taxa_engajamento'].mean():.2f}%"
)

#------tabs--------
aba1, aba2, aba3, aba4, aba5 = st.tabs([
    "Visão Geral",
    "Plataformas",
    "Conteúdo",
    "SQL",
    "Dados"
])

with aba1:

    evolucao = (
        df_filtrado
        .groupby("ano")["visualizacoes"]
        .sum()
        .reset_index()
    )

    fig, ax = plt.subplots()

    sns.lineplot(
        data=evolucao,
        x="ano",
        y="visualizacoes",
        marker="o",
        ax=ax
    )

    ax.set_title(
        "Evolução das Visualizações"
    )

    st.pyplot(fig)

with aba2: # Corrected indentation

    alcance = (
        df_filtrado
        .groupby("plataforma")["alcance"]
        .sum()
        .sort_values(ascending=False)
        .reset_index()
    )

    fig, ax = plt.subplots()

    sns.barplot(
        data=alcance,
        x="plataforma",
        y="alcance",
        ax=ax
    )

    ax.set_title(
        "Alcance por Plataforma"
    )

    st.pyplot(fig)

    eng = (
        df_filtrado
        .groupby("plataforma")
        ["taxa_engajamento"]
        .mean()
        .reset_index()
    )

    st.dataframe(eng)

with aba3: # Corrected indentation

    conteudo = (
        df_filtrado
        .groupby("tipo_conteudo")
        ["taxa_engajamento"]
        .mean()
        .sort_values(ascending=False)
        .reset_index()
    )

    fig, ax = plt.subplots()

    sns.barplot(
        data=conteudo,
        x="tipo_conteudo",
        y="taxa_engajamento",
        ax=ax
    )

    ax.set_title(
        "Engajamento por Tipo de Conteúdo"
    )

    ax.tick_params(
        axis="x",
        rotation=45
    )

    st.pyplot(fig)

with aba4: # Corrected indentation

    consulta = """
    SELECT
        plataforma,
        SUM(alcance) AS alcance_total,
        SUM(visualizacoes) AS visualizacoes_total,
        AVG(taxa_engajamento) AS engajamento_medio
    FROM redes_sociais
    GROUP BY plataforma
    ORDER BY alcance_total DESC
    """

    resultado = pd.read_sql(
        consulta,
        engine
    )

    st.dataframe(resultado)

    st.code(
        consulta,
        language="sql"
    )

with aba5: # Corrected indentation
    st.dataframe(
        df_filtrado,
        use_container_width=True
    )